backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projets"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - label: "Typographie"
        name: "font"
        widget: "select"
        options:
          - "sans-serif"
          - "serif"
          - "monospace"
          - "cursive"
